### ISSUE TITLE
Question on truncating deconvolved incidence

### ISSUE THREAD

**Issue by igoldsteinh** [JSHuisman/wastewaterRe#1]
Hello, 

I enjoyed reading your paper and have been using the code in this repository. I have a question about the code used for this method I am hoping you can help me answer. 

It appears that the final deconvolved time series of incidence values is truncated by the median of the shedding load profile distribution (specifically on line 433 of the code [here](https://github.com/covid-19-Re/shiny-dailyRe/blob/012c2892381ed8e246843556ca6ee502f134a6e0/app/otherScripts/2_utils_getInfectionIncidence.R#L433). I did not see any mention of this in the paper and I am unsure why this is being done. Can you help me better understand this part of the code? Ideally, I would like to not truncate the deconvolved incidence time series, would that be a problem? 

Thanks very much

Isaac Goldstein

**Comment by JSHuisman** [comment]
Hi Isaac,

Thank you for your interest in our method. This section of the code corresponds to the general Re estimation method, described [here](https://elifesciences.org/articles/71345#s4). If I remember correctly the reason to truncate the deconvolved incidence timeseries was because there is no/very little information for the incidence so close to the present. This part of the deconvolution is mostly informed by the right-hand padding we introduce when we shift the time series for the initial guess, and the main reason to do so is to avoid edge effects in the deconvolution. However, [@jscire](https://github.com/jscire) implemented this part of the code and might have more insights to add. 

Best,
Jana

**Comment by igoldsteinh** [comment]
Hi Jana, 

Got it, that makes sense with this set up. Thanks for taking the time to reply. 

Best,

Isaac
